### ISSUE TITLE
Table of Contents only gets built from `ePub title` comments in Content elements, not StringContent.

### ISSUE THREAD

**Issue by nicohman** [nabijaczleweli/gen-epub-book.rs#1]
Hi! I'm using this for a project of my own, but it involves generating the ePub using `StringContent` elements, rather than `Content` elements. This way, I don't have to create a file for every chapter. However, it seems that `StringContent` elements aren't scanned for the table of contents title (the `<!-- ePub title: "TOC_NAME" -->`), and the ePub just gets made with no table of contents. Could you add this feature to `StringContent` elements? Thank you for your time.

**Comment by nabijaczleweli** [comment]
Okay, so sorry for the delay, I've been in a worse state recently.
But now you can use `EPubBook::write_zip_ext(true, ...)` and `StringContent` elements will be processed for TOC decls.
I thank you for using the library and ask you if you would be so kind so as to test current `master` before I release this.

**Comment by nicohman** [comment]
Yup, this does now appear to work! Thanks!

**Comment by nabijaczleweli** [comment]
Released in [`v2.3.0`](https://github.com/nabijaczleweli/gen-epub-book.rs/releases/tag/v2.3.0).
