### ISSUE TITLE
Crashes on systems with OpenSSL 1.1.1 or higher

### ISSUE THREAD

**Issue by nicohman** [nabijaczleweli/gen-epub-book.rs#2]
This can't build on systems with OpenSSL 1.1.1 or higher because rust-openssl isn't updated enough. You need to change the reqwest dependency to `reqwest = { git = "https://github.com/seanmonstar/reqwest" }`. The reqwest master branch has the updated openssl version, but no release does yet. Thanks!

**Comment by nabijaczleweli** [comment]
I mean, I can hardly release a crate with a git dep :v
However `reqwest` 0.9.2 dropped 19 hours ago, does that version also have it?

**Comment by nicohman** [comment]
Yes, that version does have the updated version. Thanks!

**Comment by nabijaczleweli** [comment]
Does that mean this issue is resolved or do I need to bump `reqwest`'s version in the deps?

**Comment by nicohman** [comment]
Yes, you do need to bump the version to at least 0.9. Sorry for the confusion!

**Comment by nabijaczleweli** [comment]
Do please check [current `master`](https://github.com/nabijaczleweli/gen-epub-book.rs/commit/e05d01872297d7b6b34848644145934b3ef63691) if it works for ya?

**Comment by nicohman** [comment]
Yep, works perfectly! Thanks for your support.

**Comment by nabijaczleweli** [comment]
Released in [`v2.3.1`](https://github.com/nabijaczleweli/gen-epub-book.rs/releases/tag/v2.3.1)
